#!/bin/bash
#Дата.
date=$(date "+%d_%m_%Y")
#Ввод файла.
   echo "Это простая оболочка для dbf2mysql, она нужна для заливки dbf файлов в бд mysql."
#Проверка пакета.
I=`dpkg -s dbf2mysql | grep "Status" `
if [ -n "$I" ]
then
   echo "dbf2mysql установлен" 
else
   sudo apt-get install dbf2mysql
fi
   echo "Введите полный адрес к dbf файлу: "
read file
#Замена запятых на точки.
   sed -e 's/,/./g' $file > $file$date
#Данные для логина в бд.
   echo В ваш dbf файл был скопирован, его имя было изменено, его копия находится в $file$date, она будет испольоваься далее. 
   echo "Введите хост mysql(localhost): "
read host
   echo "Введите логин mysql: "
read user
   echo "Введите пароль от mysql: "
read -ers password
   echo "В вашей базе данных должна быть таблица для хранения ваших данных из dbf файлов."
   echo "Введите имя бд в которую будут заливаться файлы: "
read mysqlbase
   echo "Там будут созданы таблицы для ваших файлов с именем dbf_ИМЯ_$date, ВНИМАНИЕ! если такая таблица уже есть, она будет удалена, введите ИМЯ: "
read mysqltable
#Заливка в бд.
dbf2mysql -h $host -d $mysqlbase -t dbf_$mysqltable$date -c -U $user -P $password $file$date -vvv
#Информация о таблицах в базе.
mysql -u $user -p$password << EOF
use $mysqlbase;
show tables;
EOF


   echo "Нужно ли сделать сравнение для соцзащиты? (y/n): ";
   read yesno;                        
   if [ $yesno = "y" -o $yesno = "Y" ]; then
mysql -u $user -p$password << EOF
use $mysqlbase;
show tables;
EOF
      echo "С какой таблицей будем соединять: ?"
      read comm_table
mysql -u $user -p$password << EOF
use $mysqlbase;
SHOW COLUMNS FROM $comm_table;
EOF
      echo "По какой из колонок будем прекреплять: ?"
      read inner_column
      echo "Возвращаемся к таблице сделанной программой dbf2mysql."
      echo "Вывод колонок таблицы dbf_$mysqltable$date;."
mysql -u $user -p$password << EOF
use $mysqlbase;
SHOW COLUMNS FROM dbf_$mysqltable$date;
EOF
      echo "К какой колонке будем прекреплять: ?"
      read comm_column
      echo Соединяем
      rm output_commpare$date;
mysql -u $user -p$password $mysqlbase --execute "SELECT * FROM dbf_$mysqltable$date INNER JOIN $comm_table ON $comm_table.$inner_column = dbf_$mysqltable$date.$comm_column;" > output_commpare$date     

      echo Работа закончена, результат находится в output_commpare$date, это обычный текстовый файл.
   else
      echo Работа закончена.
   fi
