#!/bin/bash
#Дата.
date=$(date "+%d_%m_%Y")
#Ввод файла.
echo "Это простая оболочка для dbf2mysql, она нужна для заливки dbf файлов в бд mysql."
#Проверка пакета.
echo "Если пакет установлен - выполните sudo apt-get install dbf2sql"
I=`dpkg -s dbf2mysql | grep "Status" `
if [ -n "$I" ]
then
   echo "dbf2mysql установлен" 
else
   echo "dbf2mysql не установлен"
fi
echo "Введите полный адрес к dbf файлу: "
read file
#Замена запятых на точки.
sed -e 's/,/./g' $file > $file$date
#Данные для логина в бд.
echo В ваш dbf файл был скопирован, его имя было изменено, его копия находится в $file$date, она будет испольоваься далее. 
echo "Введите хост mysql(localhost): "
read host
echo "Введите логин mysql: "
read user
echo "Введите пароль от mysql: "
read -ers password
echo "В вашей базе данных должна быть таблица для хранения ваших данных из dbf файлов."
echo "Введите имя бд в которую будут заливаться файлы: "
read mysqlbase
echo "Там будут созданы таблицы для ваших файлов с именем dbfИМЯ_$date, ВНИМАНИЕ! если такая таблица уже есть, она будет удалена, введите ИМЯ: "
read mysqltable
#Заливка в бд.
dbf2mysql -h $host -d $mysqlbase -t dbf_$mysqltable$date -c -U $user -P $password $file$date -vvv
#Информация о таблицах в базе.
mysql -u $user -p$password << EOF
use $mysqlbase;
show tables;
EOF
