#!/bin/bash
#<-запись конфигурации интерфейса в файл->#
#<-IPv4->#
function select_interface_v4() 
{
    echo 'iface' $iface 'inet static'
    ifconfig $iface | grep 'inet addr' | awk '{ print $2 }' | sed 's/addr:/address /g'
    ifconfig $iface | grep 'inet addr' | awk '{ print $3 }' | sed 's/Bcast:/broadcast /g'
    ifconfig $iface | grep 'Mask' | awk '{ print $4 }' | sed 's/Mask:/netmask /g'
}
#<-IPv5->#
function select_interface_v6() 
{
    echo 'iface' $iface 'inet6 static'
#>адреса<#
for i in $(grep wlan0 /proc/net/if_inet6 | cut --output-delimiter=":" --characters=1-4,5-8,9-12,13-16,17-20,21-24,25-28,29-32);
  do echo address $i; 
done
#>маски<#
for i in $(grep wlan0 /proc/net/if_inet6  | awk '{ print $3 } '); 
 do echo "netmask" $((16#$i)); 
done
}
#<-Выбо опций->#
while getopts ":f:s:h:" optname
  do
    case "$optname" in
      "f") iface=$OPTARG
         select_interface_v4 >&2
        ;;
      "s") iface=$OPTARG
         select_interface_v6 >&2
        ;;
      "h")
        echo "help is comming:)"
        ;;
      *)
      # Соответствий не найдено
        echo "Флаг -s для ipv6 -f для ipv4"
	echo "ifsave -s wlan0" > wlan0.conf
        ;;
    esac
  done


